config/routes.rb
Rails.application.routes.draw do
  get "/pages/:page" => "pages#show"
  get '/runs/search' => 'runs#search'
  get '/runs/new_search' => 'runs#new_search'
  resources :users, except: [:index, :destroy] do
    resources :profiles, except: [:index, :destroy]
    resources :runs
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#show'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :why_i_run, length: { maximum: 140 }
  validates :experience, :user_id, presence: true
  validates :goals, length: { minimum: 15, maximum: 200 }, presence: true
  validates :need_to_knows, length: { maximum: 200 }
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/running_shoe.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ProfilesHelper
  before_action :logged_in_user, :find_and_ensure_user, :correct_user
  before_action :find_and_ensure_profile, only: [:show, :edit, :update]
  before_action :sanitize_profile_params, only: [:create, :update]

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to user_profile_path(@profile.user_id, @profile)
    else
      render 'new'
    end
  end

  def show
    @location = geocode_zip(@user)
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to user_profile_path(@profile.user_id, @profile)
    else
      render 'edit'
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:why_i_run, :goals, :user_id, :experience, :need_to_knows, :avatar)
    end

    def find_and_ensure_user
      render 'application/error_404' unless @user = User.find_by(id: params[:user_id])
    end

    def find_and_ensure_profile
      render 'application/error_404' unless @profile = current_user.profile
    end

    def sanitize_profile_params
      params['profile']['user_id'] = current_user.id
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def geocode_zip(user)
    url = "http://maps.googleapis.com/maps/api/geocode/json?"
    parameters = { address: user.zipcode, sensor: 'true' }
    response = Unirest.get(url, headers: {}, parameters: parameters)
    @location = response.body['results'][0]['address_components'][1]['short_name']
  end
end

app/views/profiles/edit.html.erb
<h2> Edit Your Profile: </h2>
<div class="container">
  <%= form_for :profile, url: user_profile_path(@profile.user_id, @profile), method: 'put' do |f| %>

    Avatar: <%= f.file_field :avatar %>
    Why I Run: <%= f.text_field :why_i_run%>
    Goals: <%= f.text_field :goals%>
    Experience Level: <br /><br />
      <%= f.select :experience, ['Beginner', 'Intermediate', 'Advanced', 'Competitive'] %>
    <br />
    Need To Knows: <%= f.text_field :need_to_knows%>
    <%= f.submit "Update Profile", :class => "waves-effect waves-light btn #00acc1 cyan darken-1" %>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <h1><%=current_user.name%>'s Profile</h1>
  <%= form_for :profile, url: { action: "create" }, html: { multipart: true }  do |f| %>
    Avatar:<%= f.file_field :avatar %>
    Why I Run: <%= f.text_field :why_i_run, placeholder:"In a few words, tell us what motivates you and keeps you running!" %>
    Goals: <%= f.text_field :goals, placeholder: "In a few words, tell us your running goals!"%>
    Experience Level: <br /><br />
      <%= f.select :experience, ['Beginner', 'Intermediate', 'Advanced', 'Competitive'] %>
    <br />

    Need To Knows: <%= f.text_field :need_to_knows, placeholder: "Is there anything important you'd want a potential running partner to know (i.e. injuries, allergies, etc.)" %>
    <%= f.submit "Create Profile", :class => "waves-effect waves-light btn #00acc1 cyan darken-1" %>

  <% end %>
</div>

app/views/profiles/show.html.erb
<div class="profile-show container center">
  <div row>
    <div class="col s6 m6 l6">
      <%= image_tag @profile.avatar.url(:medium), class: "circle responsive-image profile-pic-show-view" %>
    </div>
  </div>
  <div class = "container">
    <h2><%=@profile.user.name%>'s Profile </h2>
    <% if current_user == @profile.user %>
      <p>Email Address: <%=@profile.user.email%></p>
      <p>Location: <%=@location%></p>
    <% end %>
    <p>Why I Run: <%=@profile.why_i_run%></p>
    <p>Goals: <%=@profile.goals%></p>
    <p>Experience Level: <%=@profile.experience%></p>
    <p>Need To Knows: <%=@profile.need_to_knows%></p>
  </div>
  <% if current_user == @profile.user %>
    <div class = "container">
      <%= link_to 'Edit Profile', edit_user_profile_path(current_user, @profile) %>
    </div>
  <% end %>
</div>