config/routes.rb
Rails.application.routes.draw do
  get "/pages/:page" => "pages#show"
  get '/runs/search' => 'runs#search'
  get '/runs/new_search' => 'runs#new_search'
  resources :users, except: [:index, :destroy] do
    resources :profiles, except: [:index, :destroy]
    resources :runs
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#show'
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :runner, foreign_key: :runner_id, class_name: :User
  belongs_to :companion, foreign_key: :companion_id, class_name: :User, optional: true
  validates :runner_id, :run_date, :time, :zipcode, presence: true
  geocoded_by :zipcode
  after_validation :geocode

  def run_hours
  end

  def run_minutes
  end

  def run_daypart
  end

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  include RunsHelper
  before_action :sanitize_params, only: [:create, :update]
  # before_action :find_and_ensure_run, only: [:upvote, :declines]

  def new
    @run = Run.new
    render partial: 'runs/new_run', layout: false, locals: { run: @run }
  end

  def create
    @run = Run.new(run_params)
    if @run.save
    #   zipcode_list = retrieve_zipcodes_within_radius(@run.zipcode)
    #   matchers = search_by_date_time(zipcode_list, @run)
    #   flash[:success] = "Run saved."
    #   render partial: 'runs/run', layout: false, locals: { run: @run }
    # else
    #   @errors = run.errors.full_messages
    #   render 'new'
    end
  end

  def new_search
    if request.xhr?
      render 'new_search', layout: false
    end 
  end

  def search
     by_proximity_and_date = Run.near(current_user.zipcode, 100).where(run_date: params[:run_date])
     search_results = by_proximity_and_date.select { |run| run.runner.narrow_by_experience(current_user) } #the User model method may or may not work
  end

  def show
  end

  def edit
  end

  def update
  end

  private

  def run_params
    params.require(:run).permit(:run_date, :time, :zipcode, :mood_id, :runner_id)
  end

  def find_and_ensure_run
    render 'application/error_404' unless @run = current_user.runs.find_by(id: params[:id])
  end

  def sanitize_params
    if params[:run][:run_daypart] == 'PM'
      params[:run][:run_hours] = params[:run][:run_hours].to_i + 12
    end
    hr_sec = convert_hours_to_seconds(params[:run][:run_hours])
    min_sec = convert_minutes_to_seconds(params[:run][:run_minutes])
    params[:run][:time] = hr_sec + min_sec
    params[:run][:runner_id] = current_user.id
  end
end

app/helpers/run_helper.rb
module RunHelper
  def convert_hours_to_seconds(params)
    (params.to_i)*3600
  end

  def convert_minutes_to_seconds(params)
    (params.to_i)*60
  end

  def find_midpoint(user_coord, result_coord)
    [(user_coord[0] + result_coord[0]) / 2 , (user_coord[1] + result_coord[1]) / 2 ]
  end

  def retrieve_zipcodes_within_radius(run_zipcode)
    api_key = "" #will need to store api key as ENV
    url = "http://www.zipcodeapi.com/rest/#{api_key}/radius.json/#{run_zipcode}/2/mile"
    response = Unirest.get(url, headers: {}, parameters: {})
    nearby_zips = {}
    response.body['zip_codes'].each { |zip, distance| nearby_zips[zip['zip_code']] = zip['distance'] }
    convert_to_int = Hash[nearby_zips.map { |z,d| [z.to_i, d.to_i] }]
  end

  def nearby_runs(zipcodes)
    Run.where(zipcode: zipcodes.keys)
  end

  def search_by_date_time(zipcodes, run)
    potential_runs = nearby_runs(zipcodes)
    runs = potential_runs.where(time: run.time, run_date: run.run_date)
    runs.where.not(runner_id: current_user.id)  
  end
end

app/helpers/runs_helper.rb
module RunsHelper
  def convert_hours_to_seconds(params)
    (params.to_i)*3600
  end

  def convert_minutes_to_seconds(params)
    (params.to_i)*60
  end

  def find_midpoint(user_coord, result_coord)
    [(user_coord[0] + result_coord[0]) / 2 , (user_coord[1] + result_coord[1]) / 2 ]
  end

  def retrieve_zipcodes_within_radius(run_zipcode)
    api_key = "" #will need to store api key as ENV
    url = "http://www.zipcodeapi.com/rest/#{api_key}/radius.json/#{run_zipcode}/2/mile"
    response = Unirest.get(url, headers: {}, parameters: {})
    nearby_zips = {}
    response.body['zip_codes'].each { |zip, distance| nearby_zips[zip['zip_code']] = zip['distance'] }
    convert_to_int = Hash[nearby_zips.map { |z,d| [z.to_i, d.to_i] }]
  end

  def nearby_runs(zipcodes)
    Run.where(zipcode: zipcodes.keys)
  end

  def search_by_date_time(zipcodes, run)
    potential_runs = nearby_runs(zipcodes)
    runs = potential_runs.where(time: run.time, run_date: run.run_date)
    runs.where.not(runner_id: current_user.id)
  end
end

app/views/runs/_new.html.erb
<div class="example stopwatch" style='width: 400px; height: 250px;'></div>
<button class="btn btn-success start">Start</button>
<button class="btn btn-danger stop">Stop</button>
<button class="btn btn-info restart">Restart</button>

app/views/runs/_new_run.erb
<div class="container new-run-form" id="new-run-form">
  <h2>Plan a New Run</h2>

  <%= form_for :run, class: 'run-form-inputs', url: user_runs_path(current_user) do |f| %>
    Select a date: <%= f.text_field :run_date, class: "datepicker" %>

    Select hour: <%= f.select :run_hours, (1..12).map { |hour| hour }%> <br />
    Select minutes: <%= f.select :run_minutes, ['00', '15', '30', '45']%> <br />
    Select morning or evening: <%= f.select :run_daypart, ['AM', 'PM'] %> <br />

    Enter a zipcode: <%= f.number_field :zipcode %> <br />
    <br />

    <%= f.submit "Create Run", :class => "waves-effect waves-light btn #00acc1 cyan darken-1", id: "create-run-btn" %>
  <% end %>
</div>

app/views/runs/_run_search_button.html.erb
<div class="container" id="new-run-container">
  <div class="row">
    <%= link_to "Create Run", new_user_run_path(current_user), :class => "waves-effect waves-light btn #00acc1 cyan darken-1", id: 'start-new-run-btn' %>
    <%= link_to "Search for Run", runs_new_search_path, class: "waves-effect waves-light btn #00acc1 cyan darken-1", id: 'search-for-run-btn' %>
  </div>
</div>

app/views/runs/_upcoming_runs.erb
<h3>Upcoming Runs</h3>
<% if @user.runs.any? %>
  <h3 class='center'> Past Run Stats: </h3>
  <div class = 'container'>
    <table class='responsive-table highlight bordered'>
      <tr>
        <th>Run Date</th>
        <th>Location</th>
        <th>Companion</th>
        <th>Overall Distance</th>
        <th>Overall Time</th>
        <th>Average Pace</th>
        <th> Edit </th>
      </tr>
      <% @user.runs.each do |run| %>
      <tr>
        <td><%= run.run_date %></td>
        <td><%= run.zipcode %></td>
        <% if run.companion %>
          <td><%= run.companion.name %></td>
        <% else %>
          <td> Solo  </td>
        <% end %>
        <% if run.distance %>
          <td><%= run.distance %></td>
        <% else %>
          <td> </td>
        <% end %>
        <% if run.run_time %>
          <td><%= run.run_time %></td>
        <% else %>
          <td> </td>
        <% end %>
        <% if run.run_pace %>
          <td><%= run.run_pace %></td>
        <% else %>
          <td> </td>
        <% end %>
        <td> <%= link_to "Edit This Run", user_run_edit_stats_path(run.runner_id, run.id) %></td>
      <% end %>
    </table>
  </div>
<% else %>
  <p> You haven't had any runs yet! </p>
<% end %>

app/views/runs/edit_stats.html.erb
<h2> Edit Run Stats: </h2>
<div class="container">
  <%= form_for :run, url: user_run_update_stats_path(@run.runner_id, @run.id), method: 'put' do |f| %>
    Distance: <%= f.text_field :distance %>
    Overall Time: <%= f.text_field :run_time%>
    Average Pace: <%= f.text_field :run_pace%>
    <%= f.submit "Update Run Stats", :class => "waves-effect waves-light btn #00acc1 cyan darken-1" %>
  <% end %>
</div>

app/views/runs/new_search.html.erb
<div class="new-search-form container center">
  <div class="row">
    <div class="col s8">
      <h4>Search for a run</h4><br />
      <%= form_for :run, url: '/runs/search', method: 'GET', id: 'search-form' do |f| %>
          <div class="row">
            <div class="col s6">
              Select a date: <%= f.text_field :run_date, class: "datepicker" %>
            </div>
            <div class="col s6">
              Enter a zipcode: <%= f.number_field :zipcode %>
            </div>
          </div>
        <div class="row">
          <div class="col s4">Select hour: <%= f.select :run_hours, (1..12).map { |hour| hour } %></div>
          <div class="col s4">Select minutes: <%= f.select :run_minutes, ['00', '15', '30', '45'] %></div>
          <div class="col s4">Time of Day: <%= f.select :run_daypart, ['AM', 'PM'] %></div>
        </div>

        <%= f.submit "Find my Partner", :class => "waves-effect waves-light btn #00acc1 cyan darken-1", id: "find-partner-btn" %>
      <% end %>
    </div>
  </div>
</div>