config/routes.rb
Rails.application.routes.draw do
  get "/pages/:page" => "pages#show"
  get '/runs/search' => 'runs#search'
  get '/runs/new_search' => 'runs#new_search'
  resources :users, except: [:index, :destroy] do
    resources :profiles, except: [:index, :destroy]
    resources :runs
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'pages#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  </head>

  <body>
    <ul id="slide-out" class="side-nav fixed">
    <li><div class="userView">
      <div class="background">
        <img src="">
      </div>
    <% if logged_in? %>
    <% if current_user.profile != nil %>
      <div class="container profile-pic">
        <%= image_tag current_user.profile.avatar.url(:thumb), class: "circle profile-pic"%>
      </div><br />

      <%= link_to current_user.name , user_profile_path(current_user, current_user.profile), class: "container center" %>
    <% end %>

      <p class="container center"><%= current_user.email %></p>

    </div></li>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "The Rundown", user_path(current_user) %></li>
      <li><%= link_to "Logout", session_path(current_user), method: :delete %></li>
      <li><div class="divider"></div></li>
    <% else %>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Register", new_user_path %></li>
      <li><%= link_to "Login", new_session_path %></li>
    <% end %>

  </ul>

  <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="material-icons">menu</i></a>
    <div class="notice"><%= flash[:success] %></div>
    <div class="alert"><%= flash[:danger] %></div>
    <%= yield %>
  </head>
  <body>
    <div id="map"></div>
  </body>
</html>